// Tencent is pleased to support the open source community by making trpc-a2a-go available.
//
// Copyright (C) 2025 Tencent.  All rights reserved.
//
// trpc-a2a-go is licensed under the Apache License Version 2.0.

// Package protocol defines the core types and interfaces based on the A2A v1.0 specification.
package protocol

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// TaskState represents the lifecycle state of a task (SCREAMING_SNAKE_CASE per v1.0).
type TaskState string

// TaskState constants enumerate the v1.0 task lifecycle states.
const (
	// TaskStateUnspecified is the proto zero value (TASK_STATE_UNSPECIFIED).
	TaskStateUnspecified   TaskState = "TASK_STATE_UNSPECIFIED"
	TaskStateSubmitted     TaskState = "TASK_STATE_SUBMITTED"
	TaskStateWorking       TaskState = "TASK_STATE_WORKING"
	TaskStateInputRequired TaskState = "TASK_STATE_INPUT_REQUIRED"
	TaskStateCompleted     TaskState = "TASK_STATE_COMPLETED"
	TaskStateCanceled      TaskState = "TASK_STATE_CANCELED"
	TaskStateFailed        TaskState = "TASK_STATE_FAILED"
	TaskStateRejected      TaskState = "TASK_STATE_REJECTED"
	TaskStateAuthRequired  TaskState = "TASK_STATE_AUTH_REQUIRED"
)

// Terminal reports whether the state is a terminal lifecycle state
// (no further updates expected). Used to derive the legacy "final" stream flag.
func (s TaskState) Terminal() bool {
	switch s {
	case TaskStateCompleted, TaskStateCanceled, TaskStateFailed, TaskStateRejected:
		return true
	default:
		return false
	}
}

// MessageRole indicates the originator of a message (SCREAMING_SNAKE_CASE per v1.0).
type MessageRole string

// MessageRole constants enumerate the v1.0 message originators.
const (
	// MessageRoleUnspecified is the proto zero value (ROLE_UNSPECIFIED).
	MessageRoleUnspecified MessageRole = "ROLE_UNSPECIFIED"
	MessageRoleUser        MessageRole = "ROLE_USER"
	MessageRoleAgent       MessageRole = "ROLE_AGENT"
)

// GenerateMessageID generates a new unique message ID.
func GenerateMessageID() string {
	return "msg-" + uuid.New().String()
}

// GenerateContextID generates a new unique context ID for a task.
func GenerateContextID() string {
	return "ctx-" + uuid.New().String()
}

// GenerateTaskID generates a new unique task ID.
func GenerateTaskID() string {
	return "task-" + uuid.New().String()
}

// GenerateArtifactID generates a new unique artifact ID.
func GenerateArtifactID() string {
	return "artifact-" + uuid.New().String()
}

// GenerateRPCID generates a new unique RPC ID.
func GenerateRPCID() string {
	return uuid.New().String()
}

// ---------------------------------------------------------------------------
// Core data types (v1.0 — no "kind" fields, Part is a struct, not interface)
// ---------------------------------------------------------------------------

// Message represents a single exchange between a user and an agent.
type Message struct {
	ContextID        *string        `json:"contextId,omitempty"`
	Extensions       []string       `json:"extensions,omitempty"`
	MessageID        string         `json:"messageId"`
	Metadata         map[string]any `json:"metadata,omitempty"`
	Parts            []*Part        `json:"parts"`
	ReferenceTaskIDs []string       `json:"referenceTaskIds,omitempty"`
	Role             MessageRole    `json:"role"`
	TaskID           *string        `json:"taskId,omitempty"`
}

// Artifact represents an output generated by a task.
type Artifact struct {
	ArtifactID  string         `json:"artifactId"`
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Parts       []*Part        `json:"parts"`
	Metadata    map[string]any `json:"metadata,omitempty"`
	Extensions  []string       `json:"extensions,omitempty"`
}

// TaskStatus represents the current status of a task.
type TaskStatus struct {
	State     TaskState `json:"state"`
	Message   *Message  `json:"message,omitempty"`
	Timestamp string    `json:"timestamp,omitempty"`
}

// Task represents a unit of work being processed by the agent.
type Task struct {
	ID        string         `json:"id"`
	ContextID string         `json:"contextId"`
	Status    TaskStatus     `json:"status"`
	Artifacts []Artifact     `json:"artifacts,omitempty"`
	History   []Message      `json:"history,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
	// Extensions are the URIs of A2A extensions activated for this task.
	Extensions []string `json:"extensions,omitempty"`
}

// TaskStatusUpdateEvent indicates a change in the task's lifecycle state.
type TaskStatusUpdateEvent struct {
	TaskID    string     `json:"taskId"`
	ContextID string     `json:"contextId"`
	Status    TaskStatus `json:"status"`
	// Final is an internal hint only. The v1.0 wire format has no "final" field
	// (stream termination is signaled by the SSE stream closing). It is kept for
	// internal logic and v0-compat derivation, and is deliberately NOT serialized.
	Final    bool           `json:"-"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

// IsFinal reports whether this is a terminal status event. It derives the result
// from the task state, so it stays correct even though the v1.0 wire carries no
// explicit "final" flag.
func (e *TaskStatusUpdateEvent) IsFinal() bool {
	return e.Final || e.Status.State.Terminal() || e.Status.State == TaskStateInputRequired
}

// TaskArtifactUpdateEvent indicates a new or updated artifact chunk.
type TaskArtifactUpdateEvent struct {
	TaskID    string         `json:"taskId"`
	ContextID string         `json:"contextId"`
	Artifact  Artifact       `json:"artifact"`
	Append    *bool          `json:"append,omitempty"`
	LastChunk *bool          `json:"lastChunk,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
}

// IsFinal returns true if this is the final artifact event.
func (e *TaskArtifactUpdateEvent) IsFinal() bool {
	return e.LastChunk != nil && *e.LastChunk
}

// ---------------------------------------------------------------------------
// Request / Response types
// ---------------------------------------------------------------------------

// SendMessageParams defines the parameters for the SendMessage and
// SendStreamingMessage methods.
type SendMessageParams struct {
	RPCID         string                    `json:"-"`
	Tenant        string                    `json:"tenant,omitempty"`
	Configuration *SendMessageConfiguration `json:"configuration,omitempty"`
	Message       Message                   `json:"message"`
	Metadata      map[string]any            `json:"metadata,omitempty"`
}

// SendMessageConfiguration defines optional configuration for message sending.
type SendMessageConfiguration struct {
	AcceptedOutputModes []string                    `json:"acceptedOutputModes,omitempty"`
	PushConfig          *TaskPushNotificationConfig `json:"taskPushNotificationConfig,omitempty"`
	HistoryLength       *int                        `json:"historyLength,omitempty"`
	// ReturnImmediately replaces v0 "blocking" (inverted semantics).
	// true = do not wait for completion, false/nil = wait.
	ReturnImmediately *bool `json:"returnImmediately,omitempty"`
}

// IsBlocking returns the effective blocking flag.
// Per the v1.0 spec, returnImmediately defaults to false, meaning the server
// MUST wait for a terminal/interrupted state before returning. So an unset
// configuration (or unset ReturnImmediately) is blocking.
func (c *SendMessageConfiguration) IsBlocking() bool {
	if c == nil || c.ReturnImmediately == nil {
		return true
	}
	return !*c.ReturnImmediately
}

// TaskQueryParams defines the parameters for the GetTask method.
type TaskQueryParams struct {
	RPCID         string         `json:"-"`
	Tenant        string         `json:"tenant,omitempty"`
	ID            string         `json:"id"`
	HistoryLength *int           `json:"historyLength,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

// TaskIDParams defines parameters for methods needing only a task ID.
type TaskIDParams struct {
	RPCID    string         `json:"-"`
	Tenant   string         `json:"tenant,omitempty"`
	ID       string         `json:"id"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

// AuthenticationInfo defines authentication details a server uses when calling
// a push notification endpoint (v1.0). Scheme is required (e.g. "Bearer",
// "Basic"); Credentials is optional.
type AuthenticationInfo struct {
	Scheme      string `json:"scheme"`
	Credentials string `json:"credentials,omitempty"`
}

// PushNotificationConfig holds the delivery details for task push notifications.
// It is the internal "details" view used by SendMessageConfiguration and
// ProcessOptions; the same fields are carried directly on
// TaskPushNotificationConfig for the push-config RPC methods.
type PushNotificationConfig struct {
	ID             string              `json:"id,omitempty"`
	URL            string              `json:"url"`
	Token          string              `json:"token,omitempty"`
	Authentication *AuthenticationInfo `json:"authentication,omitempty"`
	Metadata       map[string]any      `json:"metadata,omitempty"`
}

// TaskPushNotificationConfig is the v1.0 flattened push-notification configuration.
// It is the wire type for the Create/Get/List/Delete push-config methods and for
// SendMessageConfiguration. All delivery fields live directly on this struct
// (v0 nested the details under a "pushNotificationConfig" object).
type TaskPushNotificationConfig struct {
	RPCID          string              `json:"-"`
	Tenant         string              `json:"tenant,omitempty"`
	ID             string              `json:"id,omitempty"`
	TaskID         string              `json:"taskId"`
	URL            string              `json:"url"`
	Token          string              `json:"token,omitempty"`
	Authentication *AuthenticationInfo `json:"authentication,omitempty"`
	Metadata       map[string]any      `json:"metadata,omitempty"`
}

// Details returns the delivery details of this config as a PushNotificationConfig
// (the view consumed by MessageProcessor via ProcessOptions).
func (c *TaskPushNotificationConfig) Details() *PushNotificationConfig {
	if c == nil {
		return nil
	}
	return &PushNotificationConfig{
		ID:             c.ID,
		URL:            c.URL,
		Token:          c.Token,
		Authentication: c.Authentication,
		Metadata:       c.Metadata,
	}
}

// ---------------------------------------------------------------------------
// New v1.0 operations: ListTasks / push-config list & delete
// ---------------------------------------------------------------------------

// ListTasksParams defines the parameters for the ListTasks method.
type ListTasksParams struct {
	RPCID                string         `json:"-"`
	Tenant               string         `json:"tenant,omitempty"`
	ContextID            string         `json:"contextId,omitempty"`
	Status               TaskState      `json:"status,omitempty"`
	PageSize             *int           `json:"pageSize,omitempty"`
	PageToken            string         `json:"pageToken,omitempty"`
	HistoryLength        *int           `json:"historyLength,omitempty"`
	StatusTimestampAfter string         `json:"statusTimestampAfter,omitempty"`
	IncludeArtifacts     *bool          `json:"includeArtifacts,omitempty"`
	Metadata             map[string]any `json:"metadata,omitempty"`
}

// ListTasksResult is the result of the ListTasks method.
type ListTasksResult struct {
	Tasks         []*Task `json:"tasks"`
	NextPageToken string  `json:"nextPageToken,omitempty"`
	PageSize      int     `json:"pageSize,omitempty"`
	TotalSize     int     `json:"totalSize,omitempty"`
}

// ListTaskPushNotificationConfigsParams defines the parameters for the
// ListTaskPushNotificationConfigs method.
type ListTaskPushNotificationConfigsParams struct {
	RPCID     string `json:"-"`
	Tenant    string `json:"tenant,omitempty"`
	TaskID    string `json:"taskId"`
	PageSize  *int   `json:"pageSize,omitempty"`
	PageToken string `json:"pageToken,omitempty"`
}

// ListTaskPushNotificationConfigsResult is the result of the
// ListTaskPushNotificationConfigs method.
type ListTaskPushNotificationConfigsResult struct {
	Configs       []TaskPushNotificationConfig `json:"configs"`
	NextPageToken string                       `json:"nextPageToken,omitempty"`
}

// DeleteTaskPushNotificationConfigParams defines the parameters for the
// DeleteTaskPushNotificationConfig method.
type DeleteTaskPushNotificationConfigParams struct {
	RPCID  string `json:"-"`
	Tenant string `json:"tenant,omitempty"`
	TaskID string `json:"taskId"`
	ID     string `json:"id"`
}

// GetTaskPushNotificationConfigParams defines the parameters for the
// GetTaskPushNotificationConfig method (v1.0 can address a specific config by ID).
type GetTaskPushNotificationConfigParams struct {
	RPCID  string `json:"-"`
	Tenant string `json:"tenant,omitempty"`
	TaskID string `json:"taskId"`
	ID     string `json:"id,omitempty"`
}

// ---------------------------------------------------------------------------
// SendMessageResponse — the result of message/send (discriminated union)
// ---------------------------------------------------------------------------

// SendMessageResult is the sealed Message-or-Task union returned by message/send.
// Exactly one concrete type (*Message or *Task) inhabits it, enforced by the type
// system — unlike a struct with two optional pointers where both/neither is
// representable. Mirrors the v0 SendMessageResult and the official SDK's
// SendMessageResult.
type SendMessageResult interface{ isSendMessageResult() }

func (*Message) isSendMessageResult() {}
func (*Task) isSendMessageResult()    {}

// SendMessageResponse wraps a SendMessageResult. The wrapper hosts the
// discriminating JSON (Go cannot unmarshal directly into an interface field).
type SendMessageResponse struct {
	Result SendMessageResult
}

// GetMessage returns the *Message when the result is a message, else nil.
func (r *SendMessageResponse) GetMessage() *Message {
	m, _ := r.Result.(*Message)
	return m
}

// GetTask returns the *Task when the result is a task, else nil.
func (r *SendMessageResponse) GetTask() *Task {
	t, _ := r.Result.(*Task)
	return t
}

type sendMessageResponseWire struct {
	Message *Message `json:"message,omitempty"`
	Task    *Task    `json:"task,omitempty"`
}

// MarshalJSON implements json.Marshaler.
func (r SendMessageResponse) MarshalJSON() ([]byte, error) {
	var w sendMessageResponseWire
	switch v := r.Result.(type) {
	case *Message:
		w.Message = v
	case *Task:
		w.Task = v
	}
	return json.Marshal(w)
}

// UnmarshalJSON implements json.Unmarshaler.
func (r *SendMessageResponse) UnmarshalJSON(data []byte) error {
	var w sendMessageResponseWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	switch {
	case w.Message != nil && w.Task == nil:
		r.Result = w.Message
	case w.Task != nil && w.Message == nil:
		r.Result = w.Task
	default:
		return fmt.Errorf("send message response must have exactly one of message/task")
	}
	return nil
}

// ---------------------------------------------------------------------------
// StreamResponse — a single event in message/stream SSE (discriminated union)
// ---------------------------------------------------------------------------

// StreamEvent is the sealed union of events delivered in a message/stream SSE:
// a status update, an artifact update, a full Task, or a Message. Exactly one
// concrete type inhabits it. Mirrors the v0 StreamEvent.
type StreamEvent interface{ isStreamEvent() }

func (*TaskStatusUpdateEvent) isStreamEvent()   {}
func (*TaskArtifactUpdateEvent) isStreamEvent() {}
func (*Task) isStreamEvent()                    {}
func (*Message) isStreamEvent()                 {}

// StreamResponse wraps a single StreamEvent. The wrapper hosts the discriminating
// JSON (Go cannot unmarshal directly into an interface field).
type StreamResponse struct {
	Result StreamEvent
}

// GetStatusUpdate returns the *TaskStatusUpdateEvent, or nil if not that type.
func (r *StreamResponse) GetStatusUpdate() *TaskStatusUpdateEvent {
	e, _ := r.Result.(*TaskStatusUpdateEvent)
	return e
}

// GetArtifactUpdate returns the *TaskArtifactUpdateEvent, or nil if not that type.
func (r *StreamResponse) GetArtifactUpdate() *TaskArtifactUpdateEvent {
	e, _ := r.Result.(*TaskArtifactUpdateEvent)
	return e
}

// GetTask returns the *Task, or nil if not that type.
func (r *StreamResponse) GetTask() *Task {
	t, _ := r.Result.(*Task)
	return t
}

// GetMessage returns the *Message, or nil if not that type.
func (r *StreamResponse) GetMessage() *Message {
	m, _ := r.Result.(*Message)
	return m
}

type streamResponseWire struct {
	StatusUpdate   *TaskStatusUpdateEvent   `json:"statusUpdate,omitempty"`
	ArtifactUpdate *TaskArtifactUpdateEvent `json:"artifactUpdate,omitempty"`
	Task           *Task                    `json:"task,omitempty"`
	Message        *Message                 `json:"message,omitempty"`
}

// MarshalJSON implements json.Marshaler.
func (r StreamResponse) MarshalJSON() ([]byte, error) {
	var w streamResponseWire
	switch v := r.Result.(type) {
	case *TaskStatusUpdateEvent:
		w.StatusUpdate = v
	case *TaskArtifactUpdateEvent:
		w.ArtifactUpdate = v
	case *Task:
		w.Task = v
	case *Message:
		w.Message = v
	}
	return json.Marshal(w)
}

// UnmarshalJSON implements json.Unmarshaler.
func (r *StreamResponse) UnmarshalJSON(data []byte) error {
	var w streamResponseWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	count := 0
	if w.StatusUpdate != nil {
		count++
		r.Result = w.StatusUpdate
	}
	if w.ArtifactUpdate != nil {
		count++
		r.Result = w.ArtifactUpdate
	}
	if w.Task != nil {
		count++
		r.Result = w.Task
	}
	if w.Message != nil {
		count++
		r.Result = w.Message
	}
	if count != 1 {
		return fmt.Errorf("stream response must have exactly one of statusUpdate/artifactUpdate/task/message, got %d", count)
	}
	return nil
}

// EventType returns the SSE event type string for this response.
func (r *StreamResponse) EventType() string {
	switch r.Result.(type) {
	case *TaskStatusUpdateEvent:
		return EventStatusUpdate
	case *TaskArtifactUpdateEvent:
		return EventArtifactUpdate
	case *Task:
		return EventTask
	case *Message:
		return EventMessage
	default:
		return ""
	}
}

// IsFinal returns true if this is a terminal event in the stream.
func (r *StreamResponse) IsFinal() bool {
	switch e := r.Result.(type) {
	case *TaskStatusUpdateEvent:
		return e.IsFinal()
	case *TaskArtifactUpdateEvent:
		return e.IsFinal()
	default:
		return false
	}
}

// ---------------------------------------------------------------------------
// Constructors
// ---------------------------------------------------------------------------

// NewTask creates a new Task with initial state (Submitted).
func NewTask(id, contextID string) *Task {
	return &Task{
		ID:        id,
		ContextID: contextID,
		Status: TaskStatus{
			State:     TaskStateSubmitted,
			Timestamp: time.Now().UTC().Format(time.RFC3339),
		},
		Metadata: make(map[string]any),
	}
}

// NewMessage creates a new Message with the specified role and parts.
func NewMessage(role MessageRole, parts []*Part) Message {
	return Message{
		Role:      role,
		Parts:     parts,
		MessageID: GenerateMessageID(),
	}
}

// NewMessageWithContext creates a new Message with context information.
func NewMessageWithContext(role MessageRole, parts []*Part, taskID, contextID *string) Message {
	return Message{
		Role:      role,
		Parts:     parts,
		MessageID: GenerateMessageID(),
		TaskID:    taskID,
		ContextID: contextID,
	}
}

// NewArtifactWithID creates a new Artifact with a generated ID.
func NewArtifactWithID(name, description *string, parts []*Part) *Artifact {
	return &Artifact{
		ArtifactID:  GenerateArtifactID(),
		Name:        name,
		Description: description,
		Parts:       parts,
		Metadata:    make(map[string]any),
	}
}

// NewTaskStatusUpdateEvent creates a new TaskStatusUpdateEvent.
func NewTaskStatusUpdateEvent(taskID, contextID string, status TaskStatus, final bool) TaskStatusUpdateEvent {
	return TaskStatusUpdateEvent{
		TaskID:    taskID,
		ContextID: contextID,
		Status:    status,
		Final:     final,
	}
}

// NewTaskArtifactUpdateEvent creates a new TaskArtifactUpdateEvent.
func NewTaskArtifactUpdateEvent(taskID, contextID string, artifact Artifact, lastChunk bool) TaskArtifactUpdateEvent {
	return TaskArtifactUpdateEvent{
		TaskID:    taskID,
		ContextID: contextID,
		Artifact:  artifact,
		LastChunk: &lastChunk,
	}
}

// ---------------------------------------------------------------------------
// Helper: SendMessageResponse constructors
// ---------------------------------------------------------------------------

// NewSendMessageResponseMessage wraps a Message as a SendMessageResponse.
func NewSendMessageResponseMessage(m *Message) *SendMessageResponse {
	return &SendMessageResponse{Result: m}
}

// NewSendMessageResponseTask wraps a Task as a SendMessageResponse.
func NewSendMessageResponseTask(t *Task) *SendMessageResponse {
	return &SendMessageResponse{Result: t}
}

// ---------------------------------------------------------------------------
// Helper: StreamResponse constructors
// ---------------------------------------------------------------------------

// NewStreamResponseStatusUpdate wraps a TaskStatusUpdateEvent.
func NewStreamResponseStatusUpdate(e *TaskStatusUpdateEvent) StreamResponse {
	return StreamResponse{Result: e}
}

// NewStreamResponseArtifactUpdate wraps a TaskArtifactUpdateEvent.
func NewStreamResponseArtifactUpdate(e *TaskArtifactUpdateEvent) StreamResponse {
	return StreamResponse{Result: e}
}

// NewStreamResponseTask wraps a Task.
func NewStreamResponseTask(t *Task) StreamResponse {
	return StreamResponse{Result: t}
}

// NewStreamResponseMessage wraps a Message.
func NewStreamResponseMessage(m *Message) StreamResponse {
	return StreamResponse{Result: m}
}
