// Tencent is pleased to support the open source community by making trpc-a2a-go available.
//
// Copyright (C) 2025 Tencent.  All rights reserved.
//
// trpc-a2a-go is licensed under the Apache License Version 2.0.

// Package protocol defines the core types and interfaces based on the A2A v1.0 specification.
package protocol

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// TaskState represents the lifecycle state of a task (SCREAMING_SNAKE_CASE per v1.0).
type TaskState string

const (
	// TaskStateUnspecified is the proto zero value (TASK_STATE_UNSPECIFIED).
	TaskStateUnspecified   TaskState = "TASK_STATE_UNSPECIFIED"
	TaskStateSubmitted     TaskState = "TASK_STATE_SUBMITTED"
	TaskStateWorking       TaskState = "TASK_STATE_WORKING"
	TaskStateInputRequired TaskState = "TASK_STATE_INPUT_REQUIRED"
	TaskStateCompleted     TaskState = "TASK_STATE_COMPLETED"
	TaskStateCanceled      TaskState = "TASK_STATE_CANCELED"
	TaskStateFailed        TaskState = "TASK_STATE_FAILED"
	TaskStateRejected      TaskState = "TASK_STATE_REJECTED"
	TaskStateAuthRequired  TaskState = "TASK_STATE_AUTH_REQUIRED"
)

// Terminal reports whether the state is a terminal lifecycle state
// (no further updates expected). Used to derive the legacy "final" stream flag.
func (s TaskState) Terminal() bool {
	switch s {
	case TaskStateCompleted, TaskStateCanceled, TaskStateFailed, TaskStateRejected:
		return true
	default:
		return false
	}
}

// MessageRole indicates the originator of a message (SCREAMING_SNAKE_CASE per v1.0).
type MessageRole string

const (
	// MessageRoleUnspecified is the proto zero value (ROLE_UNSPECIFIED).
	MessageRoleUnspecified MessageRole = "ROLE_UNSPECIFIED"
	MessageRoleUser        MessageRole = "ROLE_USER"
	MessageRoleAgent       MessageRole = "ROLE_AGENT"
)

// GenerateMessageID generates a new unique message ID.
func GenerateMessageID() string {
	return "msg-" + uuid.New().String()
}

// GenerateContextID generates a new unique context ID for a task.
func GenerateContextID() string {
	return "ctx-" + uuid.New().String()
}

// GenerateTaskID generates a new unique task ID.
func GenerateTaskID() string {
	return "task-" + uuid.New().String()
}

// GenerateArtifactID generates a new unique artifact ID.
func GenerateArtifactID() string {
	return "artifact-" + uuid.New().String()
}

// GenerateRPCID generates a new unique RPC ID.
func GenerateRPCID() string {
	return uuid.New().String()
}

// ---------------------------------------------------------------------------
// Core data types (v1.0 — no "kind" fields, Part is a struct, not interface)
// ---------------------------------------------------------------------------

// Message represents a single exchange between a user and an agent.
type Message struct {
	ContextID        *string        `json:"contextId,omitempty"`
	Extensions       []string       `json:"extensions,omitempty"`
	MessageID        string         `json:"messageId"`
	Metadata         map[string]any `json:"metadata,omitempty"`
	Parts            []*Part        `json:"parts"`
	ReferenceTaskIDs []string       `json:"referenceTaskIds,omitempty"`
	Role             MessageRole    `json:"role"`
	TaskID           *string        `json:"taskId,omitempty"`
}

// Artifact represents an output generated by a task.
type Artifact struct {
	ArtifactID  string         `json:"artifactId"`
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Parts       []*Part        `json:"parts"`
	Metadata    map[string]any `json:"metadata,omitempty"`
	Extensions  []string       `json:"extensions,omitempty"`
}

// TaskStatus represents the current status of a task.
type TaskStatus struct {
	State     TaskState `json:"state"`
	Message   *Message  `json:"message,omitempty"`
	Timestamp string    `json:"timestamp,omitempty"`
}

// Task represents a unit of work being processed by the agent.
type Task struct {
	ID        string         `json:"id"`
	ContextID string         `json:"contextId"`
	Status    TaskStatus     `json:"status"`
	Artifacts []Artifact     `json:"artifacts,omitempty"`
	History   []Message      `json:"history,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
}

// TaskStatusUpdateEvent indicates a change in the task's lifecycle state.
type TaskStatusUpdateEvent struct {
	TaskID    string     `json:"taskId"`
	ContextID string     `json:"contextId"`
	Status    TaskStatus `json:"status"`
	// Final is an internal hint only. The v1.0 wire format has no "final" field
	// (stream termination is signaled by the SSE stream closing). It is kept for
	// internal logic and v0-compat derivation, and is deliberately NOT serialized.
	Final    bool           `json:"-"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

// IsFinal reports whether this is a terminal status event. It derives the result
// from the task state, so it stays correct even though the v1.0 wire carries no
// explicit "final" flag.
func (e *TaskStatusUpdateEvent) IsFinal() bool {
	return e.Final || e.Status.State.Terminal() || e.Status.State == TaskStateInputRequired
}

// TaskArtifactUpdateEvent indicates a new or updated artifact chunk.
type TaskArtifactUpdateEvent struct {
	TaskID    string         `json:"taskId"`
	ContextID string         `json:"contextId"`
	Artifact  Artifact       `json:"artifact"`
	Append    *bool          `json:"append,omitempty"`
	LastChunk *bool          `json:"lastChunk,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
}

// IsFinal returns true if this is the final artifact event.
func (e *TaskArtifactUpdateEvent) IsFinal() bool {
	return e.LastChunk != nil && *e.LastChunk
}

// ---------------------------------------------------------------------------
// Request / Response types
// ---------------------------------------------------------------------------

// SendMessageParams defines the parameters for the message/send and message/stream methods.
type SendMessageParams struct {
	RPCID         string                    `json:"-"`
	Configuration *SendMessageConfiguration `json:"configuration,omitempty"`
	Message       Message                   `json:"message"`
	Metadata      map[string]any            `json:"metadata,omitempty"`
}

// SendMessageConfiguration defines optional configuration for message sending.
type SendMessageConfiguration struct {
	AcceptedOutputModes    []string                `json:"acceptedOutputModes,omitempty"`
	PushNotificationConfig *PushNotificationConfig `json:"pushNotificationConfig,omitempty"`
	HistoryLength          *int                    `json:"historyLength,omitempty"`
	// ReturnImmediately replaces v0 "blocking" (inverted semantics).
	// true = do not wait for completion, false/nil = wait.
	ReturnImmediately *bool `json:"returnImmediately,omitempty"`
}

// IsBlocking returns the effective blocking flag for backward-compatible logic.
// When ReturnImmediately is nil or false, the request is blocking.
func (c *SendMessageConfiguration) IsBlocking() bool {
	if c == nil || c.ReturnImmediately == nil {
		return false
	}
	return !*c.ReturnImmediately
}

// TaskQueryParams defines the parameters for the tasks/get method.
type TaskQueryParams struct {
	RPCID         string         `json:"-"`
	ID            string         `json:"id"`
	HistoryLength *int           `json:"historyLength,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

// TaskIDParams defines parameters for methods needing only a task ID.
type TaskIDParams struct {
	RPCID    string         `json:"-"`
	ID       string         `json:"id"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

// PushNotificationConfig represents the configuration for task push notifications (v1.0 flattened).
type PushNotificationConfig struct {
	ID       string         `json:"id,omitempty"`
	URL      string         `json:"url"`
	Token    string         `json:"token,omitempty"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

// TaskPushNotificationConfig associates a task ID with push notification settings.
type TaskPushNotificationConfig struct {
	RPCID                  string                 `json:"-"`
	PushNotificationConfig PushNotificationConfig `json:"pushNotificationConfig"`
	TaskID                 string                 `json:"taskId"`
	Metadata               map[string]any         `json:"metadata,omitempty"`
}

// ---------------------------------------------------------------------------
// SendMessageResponse — the result of message/send (discriminated union)
// ---------------------------------------------------------------------------

// SendMessageResponse wraps the result of message/send.
// Exactly one of Message or Task must be non-nil.
type SendMessageResponse struct {
	Message *Message
	Task    *Task
}

type sendMessageResponseWire struct {
	Message *Message `json:"message,omitempty"`
	Task    *Task    `json:"task,omitempty"`
}

// MarshalJSON implements json.Marshaler.
func (r SendMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(sendMessageResponseWire{
		Message: r.Message,
		Task:    r.Task,
	})
}

// UnmarshalJSON implements json.Unmarshaler.
func (r *SendMessageResponse) UnmarshalJSON(data []byte) error {
	var w sendMessageResponseWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	r.Message = w.Message
	r.Task = w.Task
	return nil
}

// ---------------------------------------------------------------------------
// StreamResponse — a single event in message/stream SSE (discriminated union)
// ---------------------------------------------------------------------------

// StreamResponse wraps a single streaming event.
// Exactly one field must be non-nil.
type StreamResponse struct {
	StatusUpdate   *TaskStatusUpdateEvent
	ArtifactUpdate *TaskArtifactUpdateEvent
	Task           *Task
	Message        *Message
}

type streamResponseWire struct {
	StatusUpdate   *TaskStatusUpdateEvent   `json:"statusUpdate,omitempty"`
	ArtifactUpdate *TaskArtifactUpdateEvent `json:"artifactUpdate,omitempty"`
	Task           *Task                    `json:"task,omitempty"`
	Message        *Message                 `json:"message,omitempty"`
}

// MarshalJSON implements json.Marshaler.
func (r StreamResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(streamResponseWire{
		StatusUpdate:   r.StatusUpdate,
		ArtifactUpdate: r.ArtifactUpdate,
		Task:           r.Task,
		Message:        r.Message,
	})
}

// UnmarshalJSON implements json.Unmarshaler.
func (r *StreamResponse) UnmarshalJSON(data []byte) error {
	var w streamResponseWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	r.StatusUpdate = w.StatusUpdate
	r.ArtifactUpdate = w.ArtifactUpdate
	r.Task = w.Task
	r.Message = w.Message
	return nil
}

// EventType returns the SSE event type string for this response.
func (r *StreamResponse) EventType() string {
	switch {
	case r.StatusUpdate != nil:
		return EventStatusUpdate
	case r.ArtifactUpdate != nil:
		return EventArtifactUpdate
	case r.Task != nil:
		return EventTask
	case r.Message != nil:
		return EventMessage
	default:
		return ""
	}
}

// IsFinal returns true if this is a terminal event in the stream.
func (r *StreamResponse) IsFinal() bool {
	switch {
	case r.StatusUpdate != nil:
		return r.StatusUpdate.IsFinal()
	case r.ArtifactUpdate != nil:
		return r.ArtifactUpdate.IsFinal()
	default:
		return false
	}
}

// ---------------------------------------------------------------------------
// Constructors
// ---------------------------------------------------------------------------

// NewTask creates a new Task with initial state (Submitted).
func NewTask(id, contextID string) *Task {
	return &Task{
		ID:        id,
		ContextID: contextID,
		Status: TaskStatus{
			State:     TaskStateSubmitted,
			Timestamp: time.Now().UTC().Format(time.RFC3339),
		},
		Metadata: make(map[string]any),
	}
}

// NewMessage creates a new Message with the specified role and parts.
func NewMessage(role MessageRole, parts []*Part) Message {
	return Message{
		Role:      role,
		Parts:     parts,
		MessageID: GenerateMessageID(),
	}
}

// NewMessageWithContext creates a new Message with context information.
func NewMessageWithContext(role MessageRole, parts []*Part, taskID, contextID *string) Message {
	return Message{
		Role:      role,
		Parts:     parts,
		MessageID: GenerateMessageID(),
		TaskID:    taskID,
		ContextID: contextID,
	}
}

// NewArtifactWithID creates a new Artifact with a generated ID.
func NewArtifactWithID(name, description *string, parts []*Part) *Artifact {
	return &Artifact{
		ArtifactID:  GenerateArtifactID(),
		Name:        name,
		Description: description,
		Parts:       parts,
		Metadata:    make(map[string]any),
	}
}

// NewTaskStatusUpdateEvent creates a new TaskStatusUpdateEvent.
func NewTaskStatusUpdateEvent(taskID, contextID string, status TaskStatus, final bool) TaskStatusUpdateEvent {
	return TaskStatusUpdateEvent{
		TaskID:    taskID,
		ContextID: contextID,
		Status:    status,
		Final:     final,
	}
}

// NewTaskArtifactUpdateEvent creates a new TaskArtifactUpdateEvent.
func NewTaskArtifactUpdateEvent(taskID, contextID string, artifact Artifact, lastChunk bool) TaskArtifactUpdateEvent {
	return TaskArtifactUpdateEvent{
		TaskID:    taskID,
		ContextID: contextID,
		Artifact:  artifact,
		LastChunk: &lastChunk,
	}
}

// ---------------------------------------------------------------------------
// Helper: SendMessageResponse constructors
// ---------------------------------------------------------------------------

// NewSendMessageResponseMessage wraps a Message as a SendMessageResponse.
func NewSendMessageResponseMessage(m *Message) *SendMessageResponse {
	return &SendMessageResponse{Message: m}
}

// NewSendMessageResponseTask wraps a Task as a SendMessageResponse.
func NewSendMessageResponseTask(t *Task) *SendMessageResponse {
	return &SendMessageResponse{Task: t}
}

// ---------------------------------------------------------------------------
// Helper: StreamResponse constructors
// ---------------------------------------------------------------------------

// NewStreamResponseStatusUpdate wraps a TaskStatusUpdateEvent.
func NewStreamResponseStatusUpdate(e *TaskStatusUpdateEvent) StreamResponse {
	return StreamResponse{StatusUpdate: e}
}

// NewStreamResponseArtifactUpdate wraps a TaskArtifactUpdateEvent.
func NewStreamResponseArtifactUpdate(e *TaskArtifactUpdateEvent) StreamResponse {
	return StreamResponse{ArtifactUpdate: e}
}

// NewStreamResponseTask wraps a Task.
func NewStreamResponseTask(t *Task) StreamResponse {
	return StreamResponse{Task: t}
}

// NewStreamResponseMessage wraps a Message.
func NewStreamResponseMessage(m *Message) StreamResponse {
	return StreamResponse{Message: m}
}

